# remote state
remote_state_key = "demo/terraform.tf.state"
remote_state_bucket = "databucketfortfs3"
remote_state_key_PR = "PROD/terraform.tf.state"
# service variables
ecs_service_name = "springbootapp"
docker_container_port = 8080
desired_task_number = "2"
spring_profile = "default"
memory = 1024