name: FB-AWS-ECS-APP-Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    if: github.ref == 'refs/heads/feature/farget-app'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: 3-application/infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Build
        run: sh deploy.sh build
        
      - name: Terraform Plan
        run: sh deploy.sh plan        

      - name: Terraform Dockerize
        run: sh deploy.sh dockerize
        
      - name: Terraform Deploy
        run: sh deploy.sh deploy        
